export interface MatchPasse {
    semaine: number;
    num_poule: string;
    competition: string;
    poule: string;
    journee: number;
    le: Date;
    horaire: Date;
    club_rec: string;
    club_vis: string;
    sc_rec: number;
    sc_vis: number;
    fdme_rec: number;
    fdme_vis: number;
    pen_rec: number;
    pen_vis: number;
    forf_rec: number;
    forf_vis: number;
    arb1_designe: string;
    arb2_designe: string;
    arb1_sifle: string;
    arb2_sifle: string;
    secretaire: string;
    chronometreur: string;
    observateur: string;
    delegue: string;
    resp_salle: string;
    tuteur_salle: string;
    code_renc: string;
    num_rec: number;
    num_vis: number;
    etat: string;
    forfait: string;
    penalite: string;
    FDME: string;
    date_arrivee: string;
}

export interface MatchAVenir {
    semaine: string;
    num_poule: string;
    competition: string;
    poule: string;
    journee: string;
    le: string;
    horaire: string;
    club_rec: string;
    club_vis: string;
    club_hote: string;
    arb1_designe: string;
    arb2_designe: string;
    observateur: string;
    delegue: string;
    code_renc: string;
    nom_salle: string;
    adresse_salle: string;
    CP: string;
    ville: string;
    colle: string;
    coul_rec: string;
    coul_gard_rec: string;
    coul_vis: string;
    coul_gar_vis: string;
    ent_rec: string;
    tel_ent_rec: string;
    corresp_rec: string;
    tel_corresp_rec: string;
    ent_vis: string;
    tel_ent_vis: string;
    corresp_vis: string;
    tel_corresp_vis: string;
    num_rec: string;
    num_vis: string;
}

export interface Match {
  semaine: number | string;
  num_poule: string;
  competition: string;
  poule: string;
  journee: number | string;
  le: Date | string | null;
  horaire: Date | string | null;
  club_rec: string;
  club_vis: string;
  club_hote?: string;
  sc_rec?: number;
  sc_vis?: number;
  fdme_rec?: number;
  fdme_vis?: number;
  pen_rec?: number;
  pen_vis?: number;
  forf_rec?: number;
  forf_vis?: number;
  arb1_designe: string | null;
  arb2_designe: string | null;
  arb1_sifle?: string;
  arb2_sifle?: string;
  secretaire?: string;
  chronometreur?: string;
  observateur?: string;
  delegue?: string;
  code_renc: string;
  nom_salle?: string;
  adresse_salle?: string;
  CP?: string;
  ville?: string;
  colle?: string;
  coul_rec?: string;
  coul_gard_rec?: string;
  coul_vis?: string;
  coul_gar_vis?: string;
  ent_rec?: string;
  tel_ent_rec?: string;
  corresp_rec?: string;
  tel_corresp_rec?: string;
  ent_vis?: string;
  tel_ent_vis?: string;
  corresp_vis?: string;
  tel_corresp_vis?: string;
  num_rec: number | string;
  num_vis: number | string;
  etat?: string;
  forfait?: string;
  penalite?: string;
  FDME?: string;
  date_arrivee?: string;
}
